version: '3'
services:
  database:
    image: postgres
    hostname: database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=aviato_app
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=aviato
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d/
volumes:
  postgres-data: